#Application Configuration
server:
  port: 8091
  error:
    include-message: always
    include-binding-errors: always

#To see h2 console in Browser
#http://localhost:8091/h2-console
#Enabling h2 console
spring:
  h2:
    console:
      enable: true
  #-----------------
  #DB
  #-----------------
  datasource:
    url: jdbc:h2:mem:productDB;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    platform: h2
    username: sa
    password:

  #-----------------
  #JPA / HIBERNATE
  #-----------------

  jpa:
    show-sql: true
    hibernate:
      ddl_auto: update
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: false
        format_sql: false
    defer-datasource-initialization: true
  logging:
    pattern:
      console: "%{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n}"
  eureka:
    client:
      serviceUrl:
        defaultZone: http://localhost:8762/eureka/      